src/Entity/Theme.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Pagerfanta\Adapter\DoctrineCollectionAdapter;
use Pagerfanta\Pagerfanta;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ThemeRepository")
 * @ORM\Table(name="themes", uniqueConstraints={
 *     @ORM\UniqueConstraint(name="themes_author_name_idx", columns={"author_id", "name"})
 * })
 */
class Theme {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var Uuid
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $name;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="ThemeRevision", mappedBy="theme", cascade={"persist"})
     * @ORM\OrderBy({"modified": "DESC"})
     *
     * @var Collection|ThemeRevision[]
     */
    private $revisions;

    public function __construct(string $name, User $author) {
        $this->id = Uuid::uuid4();
        $this->name = $name;
        $this->author = $author;
        $this->revisions = new ArrayCollection();
    }

    public function getId(): Uuid {
        return $this->id;
    }

    public function getName(): string {
        return $this->name;
    }

    public function setName(string $name) {
        $this->name = $name;
    }

    public function getAuthor(): User {
        return $this->author;
    }

    public function getLatestRevision(): ?ThemeRevision {
        $criteria = Criteria::create()
            ->orderBy(['modified' => 'DESC', 'id' => 'ASC']);

        return $this->revisions->matching($criteria)->first() ?: null;
    }

    public function addRevision(ThemeRevision $revision) {
        if (!$this->revisions->contains($revision)) {
            $this->revisions->add($revision);
        }
    }

    public function getPaginatedRevisions(int $page, int $maxPerPage = 25) {
        $pager = new Pagerfanta(new DoctrineCollectionAdapter($this->revisions));
        $pager->setMaxPerPage($maxPerPage);
        $pager->setCurrentPage($page);

        return $pager;
    }
}

src/Controller/ThemeController.php
<?php

namespace App\Controller;

use App\Entity\Theme;
use App\Entity\ThemeRevision;
use App\Form\Model\ThemeData;
use App\Form\ThemeCssType;
use App\Form\ThemeSettingsType;
use App\Repository\ThemeRepository;
use Doctrine\ORM\EntityManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ThemeController extends AbstractController {
    /**
     * @param ThemeRepository $themeRepository
     * @param int             $page
     *
     * @return Response
     */
    public function list(ThemeRepository $themeRepository, int $page) {
        return $this->render('theme/list.html.twig', [
            'themes' => $themeRepository->findAllPaginated($page),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     *
     * @param Request       $request
     * @param EntityManager $em
     *
     * @return Response
     */
    public function create(Request $request, EntityManager $em) {
        $data = new ThemeData($this->getUser());

        $form = $this->createForm(ThemeSettingsType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $theme = $data->toTheme();

            $em->persist($theme);
            $em->flush();

            $this->addFlash('success', 'flash.theme_created');

            return $this->redirectToRoute('edit_theme_css', [
                'name' => $theme->getName(),
                'username' => $theme->getAuthor()->getUsername(),
            ]);
        }

        return $this->render('theme/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Entity("theme", expr="repository.findOneByUsernameAndName(username, name)")
     * @IsGranted("ROLE_USER")
     * @IsGranted("edit", subject="theme", statusCode=403)
     *
     * @param Request       $request
     * @param EntityManager $em
     * @param Theme         $theme
     *
     * @return Response
     */
    public function editCss(Request $request, EntityManager $em, Theme $theme) {
        $data = ThemeData::createFromTheme($theme);
        $form = $this->createForm(ThemeCssType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateTheme($theme);
            $em->flush();

            $this->addFlash('success', 'flash.theme_updated');

            return $this->redirectToRoute('edit_theme_css', [
                'username' => $theme->getAuthor()->getUsername(),
                'name' => $theme->getName(),
            ]);
        }

        return $this->render('theme/edit_css.html.twig', [
            'form' => $form->createView(),
            'theme' => $theme,
        ]);
    }

    /**
     * @Entity("theme", expr="repository.findOneByUsernameAndName(username, name)")
     * @IsGranted("ROLE_USER")
     * @IsGranted("edit", subject="theme", statusCode=403)
     *
     * @param Request       $request
     * @param EntityManager $em
     * @param Theme         $theme
     *
     * @return Response
     */
    public function editSettings(Request $request, EntityManager $em, Theme $theme) {
        $data = ThemeData::createFromTheme($theme);
        $form = $this->createForm(ThemeSettingsType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateTheme($theme);
            $em->flush();

            $this->addFlash('success', 'flash.theme_updated');

            return $this->redirectToRoute('edit_theme_settings', [
                'username' => $theme->getAuthor()->getUsername(),
                'name' => $theme->getName(),
            ]);
        }

        return $this->render('theme/edit_settings.html.twig', [
            'form' => $form->createView(),
            'theme' => $theme,
        ]);
    }

    /**
     * @param Theme $theme
     * @param int   $page
     *
     * @return Response
     */
    public function history(Theme $theme, int $page) {
        return $this->render('theme/history.html.twig', [
            'theme' => $theme,
            'revisions' => $theme->getPaginatedRevisions($page),
        ]);
    }

    public function source(ThemeRevision $revision) {
        return $this->render('theme/source.html.twig', [
            'revision' => $revision,
        ]);
    }

    public function stylesheet(EntityManager $em, Request $request, string $themeId, string $field) {
        $response = new Response();
        $response->setPublic();
        $response->setImmutable();
        $response->setMaxAge(86400 * 365);
        $response->setEtag($themeId);

        if ($response->isNotModified($request)) {
            return $response;
        }

        $theme = $em->find(ThemeRevision::class, $themeId);

        if (!$theme) {
            throw new NotFoundHttpException('No such revision');
        }

        $response->setContent($theme->{'get'.ucfirst($field).'Css'}());

        return $response;
    }
}

templates/theme/_css_form.html.twig
{{ form_start(form) }}
  {{ form_row(form.parent) }}
  {{ form_row(form.commonCss, { attr: { rows: 12 } }) }}
  {{ form_row(form.dayCss, { attr: { rows: 12 } }) }}
  {{ form_row(form.nightCss, { attr: { rows: 12 } }) }}
  {{ form_row(form.comment) }}
  {{ form_row(form.appendToDefaultStyle) }}

  <div class="form__row form__button-row">
    <button class="button">{{ 'action.edit_theme'|trans }}</button>
  </div>
{{ form_end(form) }}

templates/theme/_nav.html.twig
<nav class="tabs">
  <ul class="tabs__bar unlistify">
    {% with { active: current_page == 'css' } %}
      <li>
        <a href="{{ path('edit_theme_css', { username: theme.author.username, name: theme.name }) }}"
           class="tab {{ active ? 'tab--active' }}">
          {{- 'nav.css'|trans -}}
        </a>
      </li>
    {% endwith %}

    {% with { active: current_page == 'settings' } %}
      <li>
        <a href="{{ path('edit_theme_settings', { username: theme.author.username, name: theme.name }) }}"
           class="tab {{ active ? 'tab--active' }}">
          {{- 'nav.theme_settings'|trans -}}
        </a>
      </li>
    {% endwith %}
  </ul>
</nav>

templates/theme/_settings_form.html.twig
{{ form_start(form) }}
  {{ form_row(form.name) }}

  <div class="form__row form__button-row">
    <button class="button">
      {{ (editing ? 'action.edit_theme' : 'action.create_theme')|trans }}
    </button>
  </div>
{{ form_end(form) }}

templates/theme/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'title.new_theme'|trans %}
{% block page_classes 'create-theme-page' %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {{ include('theme/_settings_form.html.twig', {
    form: form,
    editing: false
  }, with_context=false) }}
{% endblock %}

templates/theme/edit_css.html.twig
{% extends 'base.html.twig' %}

{% block title 'title.editing_theme'|trans({'%name%': theme.name}) %}
{% block page_classes 'edit-theme-css-page' %}

{% block body %}
  {{ include('theme/_nav.html.twig', {
    current_page: 'css',
    theme: theme,
  }, with_context=false) }}

  <h1 class="page-heading">{{ block('title') }}</h1>

  {{ include('theme/_css_form.html.twig', {form: form}, with_context=false) }}
{% endblock %}

templates/theme/edit_settings.html.twig
{% extends 'base.html.twig' %}

{% block title 'title.editing_theme'|trans({'%name%': theme.name}) %}
{% block page_classes 'edit-theme-settings-page' %}

{% block body %}
  {{ include('theme/_nav.html.twig', {
    current_page: 'settings',
    theme: theme,
  }, with_context=false) }}

  <h1 class="page-heading">{{ block('title') }}</h1>

  {{ include('theme/_settings_form.html.twig', {
    form: form,
    editing: true,
  }, with_context=false) }}
{% endblock %}

templates/theme/history.html.twig
{% extends 'base.html.twig' %}

{% block page_classes 'theme-history-page' %}
{% block title 'title.history_for_theme'|trans({'%theme%': '%s/%s'|format(theme.author.username, theme.name)}) %}

{% block head %}
  {{ include('_includes/meta_pagination.html.twig', {pager: revisions}, with_context=false) }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <table class="table">
    <thead>
      <tr>
        <th class="table__shrink">{{ 'label.id'|trans }}</th>
        <th class="table__shrink">{{ 'label.date'|trans }}</th>
        <th>{{ 'label.comment'|trans }}</th>
      </tr>
    </thead>
    <tbody>
      {% for revision in revisions %}
        <tr>
          {# todo: fix wrapping #}
          <td class="table__shrink">
            <a href="{{ path('theme_revision_source', {id: revision.id}) }}">
              {{ revision.id|replace({'-': '-<wbr>'})|raw }}
            </a>
          </td>
          <td class="table__shrink">
            {% with {date: revision.modified|localizeddate('long', 'short')} %}
              <time datetime="{{ revision.modified|date('c') }}" title="{{ date }}" class="relative-time">
                {{- date -}}
              </time>
            {% endwith %}
          </td>
          <td>{{ revision.comment }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {{ include('_includes/pagination.html.twig', {pager: revisions}, with_context=false) }}
{% endblock %}

templates/theme/list.html.twig
{% extends 'base.html.twig' %}

{% block title 'title.custom_themes'|trans %}
{% block page_classes 'theme-list-page' %}

{% block head %}
  {{ include('_includes/meta_pagination.html.twig', {pager: themes}, with_context=false) }}
{% endblock %}

{% block body %}
  {% from 'user/_macros.html.twig' import user_link %}

  <h1 class="page-heading">{{ block('title') }}</h1>

  <nav>
    <p><a href="{{ path('create_theme') }}" class="button">{{ 'action.new_theme'|trans }}</a></p>
  </nav>

  <table class="table">
    <thead>
      <tr>
        <th>{{ 'label.name'|trans }}</th>
        <th class="table__shrink">{{ 'label.last_revised'|trans }}</th>
        <th class="table__shrink"></th>
      </tr>
    </thead>
    <tbody>
      {% for theme in themes %}
        <tr>
          <td>{{ user_link(theme.author) }}/<strong>{{ theme.name }}</strong></td>
          <td class="table__shrink">
            {% with {date: theme.latestRevision.modified|localizeddate('long', 'short')} %}
              <time datetime="{{ theme.latestRevision.modified|date('c') }}" title="{{ date }}" class="relative-time">
                {{- date -}}
              </time>
            {% endwith %}
          </td>
          <td class="table__shrink">
            {% if is_granted('edit', theme) %}
              <a href="{{ path('edit_theme_css', {name: theme.name, username: theme.author.username}) }}"
                 class="button button--inline">
                {{- 'action.edit_theme'|trans -}}
              </a>
            {% endif %}

            <a href="{{ path('theme_history', {id: theme.id}) }}"
               class="button button--inline button--secondary">{{ 'label.history'|trans }}</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {{ include('_includes/pagination.html.twig', {pager: themes}, with_context=false) }}
{% endblock %}

templates/theme/source.html.twig
{% extends 'base.html.twig' %}

{% block html_title %}
  {{ 'title.viewing_theme_source'|trans({'%theme%': '<a href="%s">%s/%s</a>'|format(
    path('theme_history', {id: revision.theme.id})|e,
    revision.theme.author.username|e,
    revision.theme.name|e
  )})|raw }}
{% endblock %}

{% block title block('html_title')|striptags %}

{% block page_classes 'theme-source-page' %}

{% block body %}
  <h1 class="page-heading">{{ block('html_title') }}</h1>

  <p>
    <strong>{{ 'label.revision_id'|trans }}</strong>:
    <code>{{ revision.id|replace({'-': '-<wbr>'})|raw }}</code>
  </p>

  {% with {hierarchy: revision.hierarchy} %}
    {% if hierarchy|length > 1 or hierarchy[0].appendToDefaultStyle %}
      <h2>{{ 'label.hierarchy'|trans }}</h2>
      {% if hierarchy[0].appendToDefaultStyle %}
        <ul>
          <li><em>{{ 'label.default'|trans }}</em>
      {% endif %}
      {% for member in hierarchy %}
        <ul>
          <li>
            {% if member == revision %}
              <strong>{{ member.theme.author.username }}/{{ member.theme.name }}</strong>
            {% else %}
              {{ member.theme.author.username }}/{{ member.theme.name }}
            {% endif %}
            {% if member != revision %}
              (<a href="{{ path('theme_revision_source', {id: member.id}) }}">
                <code>{{- member.id|replace({'-': '-<wbr>'})|raw -}}</code>
              </a>)
            {% endif %}
      {% endfor %}
      {% for i in 0..hierarchy|length %}
          </li>
        </ul>
      {% endfor %}
      {% if hierarchy[0].appendToDefaultStyle %}
          </li>
        </ul>
      {% endif %}
    {% endif %}
  {% endwith %}

  {% if revision.commonCss is not empty %}
    <details open>
      <summary>{{ 'label.common_css'|trans }}</summary>
      <pre class="source-code"><code class="language-css">{{ revision.commonCss }}</code></pre>
    </details>
  {% endif %}

  {% if revision.dayCss is not empty %}
    <details open>
      <summary>{{ 'label.day_css'|trans }}</summary>
      <pre class="source-code"><code class="language-css">{{ revision.dayCss }}</code></pre>
    </details>
  {% endif %}

  {% if revision.nightCss is not empty %}
    <details open>
      <summary>{{ 'label.night_css'|trans }}</summary>
      <pre class="source-code"><code class="language-css">{{ revision.nightCss }}</code></pre>
    </details>
  {% endif %}
{% endblock %}