src/Entity/UserBan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserBanRepository")
 * @ORM\Table(name="user_bans")
 */
class UserBan {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var Uuid
     */
    private $id;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User", inversedBy="bans")
     *
     * @var User
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $reason;

    /**
     * @ORM\Column(type="boolean")
     *
     * @var bool
     */
    private $banned;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $bannedBy;

    /**
     * @ORM\Column(type="datetimetz")
     *
     * @var \DateTime
     */
    private $timestamp;

    /**
     * @ORM\Column(type="datetimetz", nullable=true)
     *
     * @var \DateTime|null
     */
    private $expiresAt;

    public function __construct(
        User $user,
        string $reason,
        bool $banned,
        User $bannedBy,
        \DateTime $expiresAt = null,
        \DateTime $timestamp = null
    ) {
        if (!$banned && $expiresAt) {
            throw new \DomainException('Unbans cannot have expiry times');
        }

        $this->id = Uuid::uuid4();
        $this->user = $user;
        $this->reason = $reason;
        $this->banned = $banned;
        $this->bannedBy = $bannedBy;
        $this->expiresAt = $expiresAt;
        $this->timestamp = $timestamp ?:
            \DateTime::createFromFormat('U.u', microtime(true));
    }

    public function getId(): Uuid {
        return $this->id;
    }

    public function getUser(): User {
        return $this->user;
    }

    public function getReason(): string {
        return $this->reason;
    }

    public function isBan(): bool {
        return $this->banned;
    }

    public function getBannedBy(): User {
        return $this->bannedBy;
    }

    public function getTimestamp(): \DateTime {
        return $this->timestamp;
    }

    public function getExpiresAt(): ?\DateTime {
        return $this->expiresAt;
    }

    public function isExpired(): bool {
        if ($this->expiresAt === null) {
            return false;
        }

        return $this->expiresAt < \DateTime::createFromFormat('U.u', microtime(true));
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Form\EventListener\PasswordEncodingSubscriber;
use App\Form\Model\UserData;
use App\Form\Type\HoneypotType;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

final class UserType extends AbstractType {
    /**
     * @var UserPasswordEncoderInterface
     */
    private $encoder;

    /**
     * @var AuthorizationCheckerInterface
     */
    private $authorizationChecker;

    /**
     * @param UserPasswordEncoderInterface  $encoder
     * @param AuthorizationCheckerInterface $authorizationChecker
     */
    public function __construct(
        UserPasswordEncoderInterface $encoder,
        AuthorizationCheckerInterface $authorizationChecker
    ) {
        $this->encoder = $encoder;
        $this->authorizationChecker = $authorizationChecker;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        if ($options['honeypot']) {
            $builder->add('phone', HoneypotType::class);
        }

        $editing = $builder->getData() && $builder->getData()->getEntityId();

        $builder
            ->add('username', TextType::class, [
                'help' => 'user.username_rules',
            ])
            ->add('password', RepeatedType::class, [
                'help' => 'user.password_rules',
                'property_path' => 'plainPassword',
                'required' => !$editing,
                'first_options' => ['label' => $editing ? 'user_form.new_password' : 'user_form.password'],
                'second_options' => ['label' => $editing ? 'user_form.repeat_new_password' : 'user_form.repeat_password'],
                'type' => PasswordType::class,
            ])
            ->add('email', EmailType::class, [
                'help' => 'user.email_optional',
                'required' => false,
            ]);

        if (!$editing) {
            $builder->add('verification', CaptchaType::class, [
                'as_url' => true,
                'reload' => true,
            ]);
        }

        $builder->add('submit', SubmitType::class, [
            'label' => 'user_form.'.($editing ? 'save' : 'register'),
        ]);

        $builder->addEventSubscriber(new PasswordEncodingSubscriber($this->encoder));
    }

    public function finishView(FormView $view, FormInterface $form, array $options) {
        if ($form->getData() && $form->getData()->getEntityId()) {
            // don't auto-complete the password fields when editing the user
            $view['password']['first']->vars['attr']['autocomplete'] = 'new-password';
            $view['password']['second']->vars['attr']['autocomplete'] = 'new-password';
        }
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => UserData::class,
            'honeypot' => true,
            'label_format' => 'user_form.%name%',
            'validation_groups' => function (FormInterface $form) {
                if ($form->getData()->getEntityId() !== null) {
                    $groups[] = 'edit';
                } else {
                    $groups[] = 'registration';
                }

                return $groups;
            },
        ]);

        $resolver->setAllowedTypes('honeypot', ['bool']);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Forum;
use App\Entity\User;
use App\Entity\UserBlock;
use App\Form\Model\UserBlockData;
use App\Form\Model\UserData;
use App\Form\Model\UserFilterData;
use App\Form\UserBiographyType;
use App\Form\UserBlockType;
use App\Form\UserFilterType;
use App\Form\UserSettingsType;
use App\Form\UserType;
use App\Repository\ForumBanRepository;
use App\Repository\NotificationRepository;
use App\Repository\UserRepository;
use App\Security\AuthenticationHelper;
use Doctrine\ORM\EntityManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Entity("user", expr="repository.findOneOrRedirectToCanonical(username, 'username')")
 */
final class UserController extends AbstractController {
    /**
     * @var string
     */
    private $defaultLocale;

    public function __construct(string $defaultLocale) {
        $this->defaultLocale = $defaultLocale;
    }

    /**
     * Show the user's profile page.
     *
     * @param User           $user
     * @param Request        $request
     * @param UserRepository $users
     *
     * @return Response
     */
    public function userPage(User $user, Request $request, UserRepository $users) {
        $nextUnixTime = $request->query->getInt('next_timestamp');

        if ($nextUnixTime) {
            $nextTimestamp = new \DateTime('@'.$nextUnixTime);
        }

        $contributions = $users->findContributions($user, $nextTimestamp ?? null);

        if ($nextUnixTime && !\count($contributions)) {
            throw $this->createNotFoundException('No such page');
        }

        return $this->render('user/user.html.twig', [
            'contributions' => $contributions,
            'user' => $user,
        ]);
    }

    /**
     * @param User $user
     * @param int  $page
     *
     * @return Response
     */
    public function submissions(User $user, int $page) {
        return $this->render('user/submissions.html.twig', [
            'submissions' => $user->getPaginatedSubmissions($page),
            'user' => $user,
        ]);
    }

    /**
     * @param User $user
     * @param int  $page
     *
     * @return Response
     */
    public function comments(User $user, int $page) {
        return $this->render('user/comments.html.twig', [
            'comments' => $user->getPaginatedComments($page),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("ROLE_ADMIN", statusCode=403)
     *
     * @param UserRepository $users
     * @param int            $page
     * @param Request        $request
     *
     * @return Response
     */
    public function list(UserRepository $users, int $page, Request $request) {
        $filter = new UserFilterData();
        $criteria = $filter->buildCriteria();

        $form = $this->createForm(UserFilterType::class, $filter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $criteria = $filter->buildCriteria();
        }

        return $this->render('user/list.html.twig', [
            'form' => $form->createView(),
            'page' => $page,
            'users' => $users->findPaginated($page, $criteria),
        ]);
    }

    public function registration(
        Request $request,
        EntityManager $em,
        AuthenticationHelper $authenticationHelper
    ) {
        if ($this->isGranted('ROLE_USER')) {
            return $this->redirectToRoute('front');
        }

        $data = new UserData();
        $data->setLocale($this->defaultLocale);

        $form = $this->createForm(UserType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $data->toUser();

            $em->persist($user);
            $em->flush();

            $response = $this->redirectToRoute('front');

            $authenticationHelper->login($user, $request, $response, 'main');

            $this->addFlash('success', 'flash.user_account_registered');

            return $response;
        }

        return $this->render('user/registration.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     *
     * @param EntityManager $em
     * @param User          $user
     * @param Request       $request
     *
     * @return Response
     */
    public function editUser(EntityManager $em, User $user, Request $request) {
        $data = UserData::fromUser($user);

        $form = $this->createForm(UserType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateUser($user);

            $em->flush();

            return $this->redirectToRoute('edit_user', [
                'username' => $user->getUsername(),
            ]);
        }

        return $this->render('user/edit.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     *
     * @param EntityManager $em
     * @param User          $user
     * @param Request       $request
     *
     * @return Response
     */
    public function userSettings(EntityManager $em, User $user, Request $request) {
        $data = UserData::fromUser($user);

        $form = $this->createForm(UserSettingsType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateUser($user);

            $em->flush();

            $this->addFlash('success', 'flash.user_settings_updated');

            return $this->redirect($request->getUri());
        }

        return $this->render('user/settings.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     *
     * @param EntityManager $em
     * @param User          $user
     * @param Request       $request
     *
     * @return Response
     */
    public function editBiography(EntityManager $em, User $user, Request $request) {
        $data = UserData::fromUser($user);

        $form = $this->createForm(UserBiographyType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateUser($user);

            $em->flush();

            $this->addFlash('success', 'flash.user_biography_updated');

            return $this->redirect($request->getUri());
        }

        return $this->render('user/edit_biography.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("edit_user", subject="user", statusCode=403)
     *
     * @param User $user
     * @param int $page
     *
     * @return Response
     */
    public function blockList(User $user, int $page) {
        return $this->render('user/block_list.html.twig', [
            'blocks' => $user->getPaginatedBlocks($page),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Entity("blockee", expr="repository.findOneOrRedirectToCanonical(username, 'username')")
     *
     * @param User          $blockee
     * @param Request       $request
     * @param EntityManager $em
     *
     * @return Response
     */
    public function block(User $blockee, Request $request, EntityManager $em) {
        /* @var User $blocker */
        $blocker = $this->getUser();

        if ($blocker->isBlocking($blockee)) {
            throw $this->createNotFoundException('The user is already blocked');
        }

        $data = new UserBlockData();

        $form = $this->createForm(UserBlockType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $block = $data->toBlock($blocker, $blockee);

            $em->persist($block);
            $em->flush();

            $this->addFlash('success', 'flash.user_blocked');

            return $this->redirectToRoute('user_block_list', [
                'username' => $blocker->getUsername(),
            ]);
        }

        return $this->render('user/block.html.twig', [
            'blockee' => $blockee,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Security("user === block.getBlocker()", statusCode=403)
     *
     * @param UserBlock     $block
     * @param EntityManager $em
     * @param Request       $request
     *
     * @return Response
     */
    public function unblock(UserBlock $block, EntityManager $em, Request $request) {
        $this->validateCsrf('unblock', $request->request->get('token'));

        $em->remove($block);
        $em->flush();

        $this->addFlash('success', 'flash.user_unblocked');

        return $this->redirectToRoute('user_block_list', [
            'username' => $this->getUser()->getUsername(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     *
     * @param int $page
     *
     * @return Response
     */
    public function notifications(int $page) {
        /* @var User $user */
        $user = $this->getUser();

        return $this->render('user/notifications.html.twig', [
            'notifications' => $user->getPaginatedNotifications($page),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     *
     * @param Request                $request
     * @param NotificationRepository $nr
     * @param EntityManager          $em

templates/user/_macros.html.twig
{##
 # - submitter (bool): If comment author is the submission author
 # - flag (int|string): one of App\Entity\UserFlags constants, or 'admin'/'moderator'
 # - class (string): Additional classes
 #}
{%- macro user_link(user, options) -%}
  {%- from _self import _class_by_flag -%}
  <a href="{{ path('user', {username: user.username}) }}"
     class="{{ (options.submitter ?? false) ? 'submitter' }} {{ _class_by_flag(options.flag ?? 0) }} {{ options.class ?? '' }}">
    {{- (options.prefix ?? false) ? '/u/' -}}
    {{- user.username -}}
  </a>
  {%- if options.flag ?? 0 is same as(0) -%}
  {% elseif options.flag == constant('App\\Entity\\UserFlags::FLAG_ADMIN') or options.flag == 'admin' %}
    <small class="user-flag user-flag-admin">{{ 'user_flag.admin'|trans }}</small>
  {% elseif options.flag == constant('App\\Entity\\UserFlags::FLAG_MODERATOR') or options.flag == 'moderator' %}
    <small class="user-flag user-flag-moderator">{{ 'user_flag.moderator'|trans }}</small>
  {%- endif -%}
{%- endmacro -%}

{%- macro _class_by_flag(flag) -%}
  {%- if flag is same as(0) -%}
    {#- early exit -#}
  {%- elseif flag == constant('App\\Entity\\UserFlags::FLAG_ADMIN') or flag == 'admin' -%}
    flag-admin
  {%- elseif flag == constant('App\\Entity\\UserFlags::FLAG_MODERATOR') or flag == 'moderator' -%}
    flag-moderator
  {%- endif -%}
{%- endmacro -%}

templates/user/_nav.html.twig
<nav class="tabs user-nav">
  <ul class="unlistify tabs__bar">
    {% for tab in [
      { path: 'user', label: 'label.overview' },
      { path: 'user_submissions', label: 'user.submissions' },
      { path: 'user_comments', label: 'user.comments' },
    ] %}
      <li>
        <a href="{{ path(tab.path, {username: user.username}) }}"
           class="tab {{ tab.path == current ? 'tab--active' }}">
          {{- tab.label|trans -}}
        </a>
      </li>
    {% endfor %}
  </ul>
</nav>

<h1 class="page-heading break-text no-desktop">{{ user.username }}</h1>

templates/user/base.html.twig
{% extends 'base.html.twig' %}

{% from _self import timestamp %}

{% block sidebar %}
  <section class="sidebar__section user-bio">
    <h1 class="sidebar__title user-bio__title break-text">
      <a href="{{ path('user', {username: user.username}) }}" class="user-bio__user-link">{{ user.username }}</a>
    </h1>

    <p class="user-bio__registered">{{ 'user.registered'|trans({
      '%timestamp%': timestamp(user.created)
    })|raw }}</p>

    {% if user.biography is not empty %}
      <div class="user-bio__biography">{{ user.biography|cached_markdown({ context: 'user_biography', user: user })|raw }}</div>
    {% endif %}
  </section>

  {% set toolbox_items = [] %}

  {% if is_granted('ROLE_USER') and user is not same as(app.user) %}
    {% if is_granted('message', user)  %}
      {% set item %}
        <li><a href="{{ path('compose_message', {username: user.username}) }}">{{ 'user.message'|trans }}</a></li>
      {% endset %}
      {% set toolbox_items = toolbox_items|merge([item]) %}
    {% endif %}

    {% if not app.user.isBlocking(user) %}
      {% set item %}
        <li><a href="{{ path('block_user', {username: user.username}) }}">{{ 'nav.block_user'|trans }}</a></li>
      {% endset %}
      {% set toolbox_items = toolbox_items|merge([item]) %}
    {% endif %}

    {% if is_granted('ROLE_ADMIN') %}
      {% set item %}
        {% if not user.banned %}
          <li><a href="{{ path('ban_user', {username: user.username}) }}">{{ 'action.ban'|trans }}</a></li>
        {% else %}
          <li><a href="{{ path('unban_user', {username: user.username}) }}">{{ 'action.unban'|trans }}</a></li>
        {% endif %}
      {% endset %}
      {% set toolbox_items = toolbox_items|merge([item]) %}

      {% set item %}
        <li><a href="{{ path('user_forum_bans', {username: user.username}) }}">{{ 'nav.forum_bans'|trans }}</a></li>
      {% endset %}
      {% set toolbox_items = toolbox_items|merge([item]) %}
    {% endif %}
  {% endif %}

  {% if user is same as(app.user) %}
    {% set item %}
      <li><a href="{{ path('edit_biography', {username: user.username}) }}">{{ 'nav.edit_biography'|trans }}</a></li>
    {% endset %}
    {% set toolbox_items = toolbox_items|merge([item]) %}

    {% set item %}
      <li><a href="{{ path('hidden_forums', {username: user.username}) }}">{{ 'nav.hidden_forums'|trans }}</a></li>
    {% endset %}
    {% set toolbox_items = toolbox_items|merge([item]) %}
  {% endif %}

  {% if toolbox_items %}
    <section class="sidebar__section sidebar__section--user-toolbox">
      <h1 class="sidebar__title">{{ 'label.toolbox'|trans }}</h1>
      <ul class="sidebar__list unlistify">
        {% for item in toolbox_items %}
          {{ item }}
        {% endfor %}
      </ul>
    </section>
  {% endif %}

  {% if is_granted('ROLE_ADMIN') %}
    <section class="sidebar__section sidebar__section--user-roles">
      <h1 class="sidebar__title">{{ 'heading.user_roles'|trans }}</h1>
      <form action="{{ path(user.trusted ? 'mark_user_untrusted' : 'mark_user_trusted', {username: user.username}) }}" method="post" class="form">
        <input type="hidden" name="token" value="{{ csrf_token('mark_trusted') }}">
        <div class="form__row">
          <button class="button button--secondary">{{ (not user.trusted ? 'action.mark_as_trusted' : 'action.mark_as_untrusted')|trans }}</button>
        </div>
      </form>
    </section>
  {% endif %}

  {% if user.moderatorTokens|length > 0 %}
    <section class="sidebar__section sidebar__section--user-moderator-info">
      <h1 class="sidebar__title break-text">{{ 'user.moderates'|trans({'%username%': user.username}) }}</h1>
      <ul>
        {% for token in user.moderatorTokens %}
          <li><a href="{{ path('forum', {forum_name: token.forum.name}) }}">{{ token.forum.name }}</a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
{% endblock %}

{%- macro timestamp(timestamp) -%}
  {%- set date = timestamp|localizeddate('long', 'short') -%}
  <time datetime="{{ timestamp|date('c') }}" class="relative-time" title="{{ date }}">
    {{- 'time.on_timestamp'|trans({'%timestamp%': date}) -}}
  </time>
{%- endmacro -%}

templates/user/block.html.twig
{% extends 'base.html.twig' %}
{% from 'user/_macros.html.twig' import user_link %}

{% block page_classes 'user-block-page' %}
{% block title 'title.blocking_user'|trans({'%user%': '/u/'~blockee.username}) %}

{% block body %}
  <h1 class="page-heading">
    {{ 'title.blocking_user'|trans({
      '%user%': user_link(blockee, {prefix: true}),
    })|raw }}
  </h1>

  <div class="alert alert--notice">
    <p>{{ 'help.block_users'|trans }}</p>
  </div>

  {{ form(form) }}
{% endblock %}

templates/user/block_list.html.twig
{% extends 'base.html.twig' %}

{% block page_classes 'user-block-list-page' %}
{% block title 'title.block_list'|trans %}

{% from 'user/_macros.html.twig' import user_link %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  <div class="alert alert--notice">
    <p>{{ 'help.block_users'|trans }}</p>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th class="table__shrink">{{ 'label.username'|trans }}</th>
        <th class="table__shrink">{{ 'label.blocked'|trans }}</th>
        <th>{{ 'label.comment'|trans }}</th>
        <th class="table__shrink"></th>
      </tr>
    </thead>
    <tbody>
      {% for block in blocks %}
        <tr>
          <td class="table__shrink">{{ user_link(block.blocked) }}</td>
          <td class="table__shrink">
            {% with {date: block.timestamp|localizeddate('long', 'short')} %}
            <time datetime="{{ block.timestamp|date('c') }}" title="{{ date }}" class="relative-time">
              {{- date -}}
            </time>
            {% endwith %}
          </td>
          <td>{{ block.comment }}</td>
          <td class="table__shrink">
            <form action="{{ path('unblock_user', {id: block.id}) }}" method="post">
              <input type="hidden" name="token" value="{{ csrf_token('unblock') }}">
              <button class="button button--inline">{{ 'action.unblock'|trans }}</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}
{% from '_macros/icon.html.twig' import icon %}

{% block title 'edit_user.title'|trans({'%username%': user.username}) %}

{% block page_classes %}edit-user-page{% endblock %}

{% block body %}
  <h1 class="page-heading break-text">{{ block('title') }}</h1>

  {% if app.user != user %}
    <div class="alert alert--warn">
      <p>
        <span class="fg-orange">{{ icon('attention') }}</span>
        {{ 'flash.editing_credentials_of_other_user'|trans }}
      </p>
    </div>
  {% endif %}

  {% include 'user/_form.html.twig' %}
{% endblock %}

templates/user/edit_biography.html.twig
{% extends 'user/base.html.twig' %}

{% block title 'title.editing_biography_for_user'|trans({'%user%': user.username}) %}

{% block body %}
  <h1>
    {{ 'title.editing_biography_for_user'|trans({
      '%user%': '<a href="%s">/u/%s</a>'|format(path('user', {username: user.username})|e, user.username|e)
    })|raw }}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.biography, {attr: {rows: 5}}) }}

    {{ form_row(form.save) }}
  {{ form_end(form) }}
{% endblock %}

templates/user/hidden_forums.html.twig
{% extends 'user/base.html.twig' %}

{% block title 'title.hidden_forums'|trans %}

{% block head %}
  {{ parent() }}

  {{ include('_includes/meta_pagination.html.twig', {pager: forums}, with_context=false) }}
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ 'title.hidden_forums'|trans }}</h1>

  <div class="alert alert--notice">
    <p>{{ 'help.hidden_forums'|trans }}</p>
    <p>{{ 'help.hidden_forums_no_comment_hiding'|trans }}</p>
  </div>

  {% if forums|length > 0 %}
    <table class="table">
      <thead>
        <tr>
          <th class="table__shrink">{{ 'forum_list.name'|trans }}</th>
          <th>{{ 'forum_list.title'|trans }}</th>
          <th class="table__shrink"></th>
        </tr>
      </thead>

      <tbody>
      {% for forum in forums %}
        <tr>
          <td class="table__shrink">
            <a href="{{ path('forum', {forum_name: forum.name}) }}"><strong>{{ forum.name }}</strong></a>

            {% if forum.featured %}
              <span title="{{ 'help.forum_is_featured'|trans }}">&#x2b50;</span>
            {% endif %}
          </td>

          <td>{{ forum.title }}</td>

          <td class="table__shrink">
            <form action="{{ path('unhide_forum', {username: user.username, forum: forum.id}) }}" method="POST">
              <input type="hidden" name="token" value="{{ csrf_token('hide_forum') }}">
              <button class="button button--inline">{{ 'action.delete'|trans }}</button>
            </form>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    {{ include('_includes/pagination.html.twig', {pager: forums}, with_context=false) }}
  {% else %}
    <p><small class="dimmed">{{ 'flash.no_entries_to_display'|trans }}</small></p>
  {% endif %}
{% endblock %}

templates/user/registration.html.twig
{% extends 'base.html.twig' %}

{% block page_classes %}registration-page{% endblock %}
{% block title 'title.sign_up'|trans %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {% include 'user/_form.html.twig' %}
{% endblock %}